### PR TITLE
fix(terraform): add apex_domain* variables and deprecate parent_domain* variables

### PR DESCRIPTION
**Pull request by hervelemeur**
Related PR: https://github.com/jx3-gitops-repositories/jx3-terraform-gke/pull/30

Related [slack thread](https://kubernetes.slack.com/archives/C9LTHT2BB/p1607443301111500)

More coherent with the TLS doc and the other gitops templates.

### CODE REVIEW

**Comment by rawlingsj** [comment]
thanks @hervelemeur

**Comment by rawlingsj** [comment]
@hervelemeur I'm going to push a change to your PR if you don't mind.  The pipeline has not been migrated to jx3 yet and is using an old GC'd image.  I think I have a fix.

**Comment by hervelemeur** [comment]
@rawlingsj  np, go for it ;)

**Comment by rawlingsj** [comment]
thanks :) the pipeline is running now although it had a test failure sorry..
```
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unsupported argument

  on variables.tf line 58, in variable "parent_domain":
  58:   deprecation = "Please use apex_domain_gcp_project variable instead."

An argument named "deprecation" is not expected here.


Error: Unsupported argument

  on variables.tf line 71, in variable "parent_domain_gcp_project":
  71:   deprecation = "Please use apex_domain_gcp_project variable instead."

An argument named "deprecation" is not expected here.

make: *** [init] Error 1
```

**Comment by rawlingsj** [comment]
that was after the pipeline ran `terraform init`

**Comment by rawlingsj** [comment]
just checking what version of terraform is in the pipeline, looks like its TERRAFORM 0.13.5, could that be related?

**Comment by hervelemeur** [comment]
@rawlingsj Maybe, I've jsut updated terraform to 0.14.0, I didn't had any error.

If you know how I could mark these inputs as deprecated with something else than `deprecation` I'll update the PR

I can also just put "(Deprecated) " at the beggining of their description instead.

**Comment by rawlingsj** [comment]
yeah think it must be a 0.14 thing, I was just pushing the same idea as you for the description, hopefully thats enough for now and we can move to 0.14 and the nicer deprecations soon

**Comment by rawlingsj** [comment]
great - past that issue, just need to run `make lint` and fix the extra spaces in front of the new var in main.tf and align the two var underneath

**Comment by hervelemeur** [comment]
OK :)

I've updated the related PR in the meantime.

**Comment by hervelemeur** [comment]
@rawlingsj had to [update the supported terraform version](https://github.com/jenkins-x/terraform-google-jx/pull/166) before running `make lint`, then got this in return:

> make: \*\*\* \[fmt\] Error 3

I've pushed with a space to align the variable, not sure where there are spaces missing elsewhere.

**Comment by rawlingsj** [comment]
Ok - lemme push the fix to your repo and lets tackle the terraform 0.14 later in the week as its not needed for beta and we've still a lot of work to get through tonight for the beta release aiming tomorrow.

**Comment by rawlingsj** [comment]
ok pushed - lets see if CI prefers that

**Comment by hervelemeur** [comment]
Thanks, and sorry to add some work to your already overfull day ^^

**Comment by rawlingsj** [comment]
Not a problem at all!  This is all awesome, plus I'm planning on updating the TLS and DNS docs tonight if all goes well with th beta and this PR from you really helps :)

**Comment by rawlingsj** [comment]
CI failed as SAs were being GC'd by another processes, will move over to JX v3 soon but for now
/override pr-build 
/lgtm

**Pull request merged**
