### PR TITLE
feat: add project name to requirements filename

### PR DESCRIPTION
**Pull request by cagiti**

### CODE REVIEW

**Comment by hferentschik** [comment]
@cagiti - what is the reason for this change? What do you gain by having the project name in the requirements file? 

The reason for using the default name is that it becomes easier to document everything. If we were to change the name we also need to update the README as well as jx-docs using even more "meta" names. 

Personally I don't really see the benefit really and if one really wanted to one can manually rename the file. Also, the templated file is just "temporary". Once you run `jx boot`, it is the `jx-requirements.yaml` in the boot repository which is the relevant one. To a certain degree, it is even a bad idea to template the requirements. See issue #73 . 
Better separation of concerns would be if the Terraform module just defines the necessary outputs which one then has to fill into a requirements file. It's a trade-off really.

**Comment by cagiti** [comment]
> @cagiti - what is the reason for this change? What do you gain by having the project name in the requirements file?

*Background*: we manage all of the infrastructure for a suite of Jenkins X clusters using the same repository... as a result we've found that when using this module for more than one clusters' resources we experience a clash with the `local_file` output as its name is static. The first option which came to mind was to raise this PR and prefix which solves this issue.

> The reason for using the default name is that it becomes easier to document everything. If we were to change the name we also need to update the README as well as jx-docs using even more "meta" names.

I agree, any step towards making that easier is always a good thing 👍 .

> Personally I don't really see the benefit really and if one really wanted to one can manually rename the file. Also, the templated file is just "temporary". Once you run `jx boot`, it is the `jx-requirements.yaml` in the boot repository which is the relevant one. To a certain degree, it is even a bad idea to template the requirements. See issue #73 .
> Better separation of concerns would be if the Terraform module just defines the necessary outputs which one then has to fill into a requirements file. It's a trade-off really.

You raise some valid questions, and yes perhaps the intent would be to ignore the local_file created by this module as it should only be used for the initial install. However without the following [change](https://github.com/jenkins-x/terraform-google-jx/pull/87) (_that's if using the lifecycle directive for the filename is effective_) terraform would always try and recreate the `local_file` if deleted/renamed or update it if changed.

**Comment by hferentschik** [comment]
> The first option which came to mind was to raise this PR and prefix which solves this issue.

Could we have an optional prefix to the local file name? Something like `"${path.cwd}/{var.requirements_prefix}jx-requirements.yml"`
I would not be as dynamic I guess since you would be forced to explicitly set the prefix to the project id (if that's what you want), but it would keep the default and offer a more generic approach allowing for any sort of prefix.

**Comment by hferentschik** [comment]
> terraform would always try and recreate the local_file if deleted/renamed or update it if changed.

Which is pretty much the intention right now. The idea is that on the first run you can literally use the generated jx-requirements.yaml as is. Then if you change anything which would result in changes to the requirements, the file gets updated and you would select the required change from _jx_requirements.yaml_ and transfer/sync it to the requirements in the actual boot config. Absolutely not ideal, but I fear the alternative is even worse. I feel more and more that the whole templating created more issues and confusion than it solves.

**Comment by hferentschik** [comment]
@cagiti wdyt about

> Could we have an optional prefix to the local file name? Something like "${path.cwd}/{var.requirements_prefix}jx-requirements.yml"

How important is this for you?

**Comment by cagiti** [comment]
I think for simplicity this [PR](https://github.com/jenkins-x/terraform-google-jx/pull/87/files) should be considered over this PR for simplicity.

**Comment by cagiti** [comment]
On the basis of my above ☝️ comment I'll close this

**Pull request closed without merging**
