### PR TITLE
Use a private cluster instead of a public one

### PR DESCRIPTION
**Pull request by heroic**
Ideally, we should have a flag to change between public and private, but I don't see any reason to use a public cluster in a production cluster.

### CODE REVIEW

**Comment by rawlingsj** [comment]
@heroic thanks for the PR.  We need to be able to support existing jx2 users setups and also handle upgrades.  There's quite a bit of change in this PR so I wonder if we need to split it down a bit, avoid the changing of defaults and also rebase the PR.  We can then start to review it if that's ok.

**Comment by heroic** [comment]
@rawlingsj I have removed all the changes to the defaults. Let me know what else breaks backward compatibility here.

**Comment by m1pl** [comment]
@rawlingsj What is missing to get this moving forward? This is needed for stuff like VPC peering and static outbound IP address.

**Comment by m1pl** [comment]
@heroic Maybe you could start by rebasing and squashing commits to clean up the history?

**Pull request closed without merging**
