### PR TITLE
fix: add better v3 requirements file

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by hervelemeur** [comment]
@jstrachan some of these variables have nothing in relation with the infrastructure (like Dev Env Approvers), wouldn't it be better to keep/define them only in the cluster repo?

**Comment by jstrachan** [comment]
@hervelemeur any specifics you had in mind? TBH the main motivation was to avoid the old breaking requirements syntax on v3 ;) - but we can definitely remove more stuff thats not cloud infrastructure related like `environmentGitOwner`. The project + cluster name could be generated via TF so left that in - I've just pushed a smaller version

**Comment by jstrachan** [comment]
@hervelemeur wanna see if there's anything in the latest commit you thought we should zap?

**Comment by hervelemeur** [comment]
@jstrachan LGTM :)

It would be good to have [the same terraform inputs](https://github.com/jx3-gitops-repositories/jx3-terraform-azure#terraform-inputs) regardless of the cloud providers.

**Pull request merged**
