### PR TITLE
fix: modified version constraint on kubernetes provider to monkey patch and stop breaking change upgrade until module can be refactored to function on latest 2.x provider

### PR DESCRIPTION
**Pull request by chrismellard**

### CODE REVIEW

**Comment by rawlingsj** [comment]
fixes https://github.com/jenkins-x/terraform-google-jx/issues/173

**Comment by rawlingsj** [comment]
@chrismellard mind fixing up the commit message as well please?

**Comment by chrismellard** [comment]
alright.. before I rage quit can someone pull the logs please?

**Comment by rawlingsj** [comment]
This repo and a few others are on old v2 infra, there's an issue with that infra so we're going to move it to v3 although that wont be until next week.  So we'll need to wait for that.

**Comment by rawlingsj** [comment]
the old v2 infra is ok again now, we'll still need to move to v3 but think we can still try and get this fix in.

fwiw its the [make lint](https://github.com/jenkins-x/terraform-google-jx/blob/8e480aab6dde0729d6513dcb6fce560b6082f77b/jenkins-x.yml#L27-L29) thats failing

**Comment by chrismellard** [comment]
🤷 I get a pass locally - 
image

**Comment by chrismellard** [comment]
Must be some bad linting for tf 0.13 I'd guess but I don't have that locally

**Comment by chrismellard** [comment]
Looks like that fix has merged from another PR anyway so this is redundant. The only other diffs in this PR were tf 0.14 linting fixes which I suspect is why tf 0.13 linting is reporting a failure. Irony.

**Pull request closed without merging**
