### PR TITLE
chore: update terraform-docs to in-place update README

### PR DESCRIPTION
**Pull request by khos2ow**
terraform-docs v0.12 added support for --output-file which can be used
alongside --output-mode inject to in-place update the content inside a
target file (e.g. README.md).

This also adds '.terraform-docs.yml' file for better user experience and
consistency across team members.

### CODE REVIEW

**Review by khos2ow — COMMENTED** [review]
I've separated the changes into two commits, main one to review is 9150cb0. The second one (2057d9f) is to enable `anchors` for input and outputs items.

Let me know if you'd like to keep this change (and I can squash them) or revert it.

**Comment by khos2ow** [comment]
@jstrachan bot said to ping Cai but maybe you can take a look at this too?

**Comment by msvticket** [comment]
I've rebased on master and run `make markdown-table` to resolve conflict

/ok-to-test

**Pull request merged**
