### PR TITLE
feat: added in vault chart as cluster dependency

### PR DESCRIPTION
**Pull request by chrismellard**

### CODE REVIEW

**Comment by rawlingsj** [comment]
if this merges will it mean that two vaults will be installed when using the jx v3 https://github.com/jx3-gitops-repositories/jx3-gke-vault template?  

Also another thought, what happens for folks upgrading this terraform module once this merges?  Will there be a conflict for folks that already have vault installed?

**Comment by chrismellard** [comment]
Yes, two vaults in different namespaces temporarily.... Therefore we'll also need to remove it from helmfile in the template repo.... What is the process for removing it from existing folks helmfiles? Could put it in `jx gitops upgrade` custom boot process?

**Comment by chrismellard** [comment]
Additional thought to the above. We've no way of synchronising `jx gitops upgrade` with a `terraform init + apply`. We need a way (ideally) of a terraform upgrade removing the config from helmfile. Sounds hard.

**Comment by jstrachan** [comment]
the migration is tricky isn't it. 

wonder if we need a way to configure that vault is installed via Terraform; so at least we can then expose that fact into the `jx-requirements.yml` then we can at least alert the user in their next `jx gitops upgrade` that the vault is now installed in a different namespace & so that the vault in the helmfile should be removed.

e.g. if folks use the `vault in terraform` option, we export this flag to the `jx-requirements.yml` in some canonical location so that we know there should not be a local vault installed?

**Comment by chrismellard** [comment]
nice idea. extending that we could use the helmfile `condition` flag against the vault release. In theory we could add this yaml key in via `gitops upgrade`

**Comment by jstrachan** [comment]
yeah - I'd be tempted to just leave this migration to `jx gitops upgrade` (as we can include some help and stuff) and just remove vault from helmfile once folks upgrade TF - as long term we'll wanna remove it from helmfile.

**Pull request merged**
